### ISSUE TITLE
Disappearing act!

### ISSUE THREAD

**Issue by robinwkurtz** [toddmotto/flaunt-js#1]
Hello,

Thank you for your great work, I'm very happy to have been able to use your script in my work. I have a small issue, or rather I noticed a little hiccup that you may or may not know about. On your demo page, if you scale your window down to a mobile view to reveal the mobile nav, activate it, deactivate it then scale your window back to any larger size, the "desktop" menu doesn't reappear.

You can then either refresh the page or scale the window back down to mobile to have the menu reappear.

Issue seen in recent Safari and Firefox running on OS X

Any ideas of why this would be?
Thanks

**Comment by onthecape** [comment]
Robin, just ran into this problem a couple hours ago myself.  I fixed it by adding the following the flaunt.js demo.css file:

@media only screen and (min-width: 769px) {
    .nav-list {
        display: block;
        overflow: visible !important;
    }
}

Hope this helps!

**Comment by robinwkurtz** [comment]
Unfortunately it's not working for me. However I have only tried to locally.

![flaunt_js_fix_ss](https://f.cloud.github.com/assets/4428953/805676/4421acae-ee2b-11e2-816c-7eba32e891bf.png)

**Comment by robinwkurtz** [comment]
Was able to fix the from myself with the following,

@media only screen and (min-width: 769px) {
.nav-list {
display: block !important;
overflow: visible !important;
}
}

Only issue I am having now, is on and iPad and iPhone, one of the menus loads open when turned to landscape... however no issue when scaling the window on a desktop.
